// app/keyboard-layout.ts — the touch keyboard's keys. Written by
// `bun run keyboard` (scripts/keyboard-editor.ts); hand edits are fine and
// survive a round trip, but comments and formatting do not. The format and its
// checks are in shared/keyboard.ts.

import type { KeyboardLayout } from "../shared/keyboard.ts";

export const KEYBOARD_LAYOUT: KeyboardLayout = {
  actionRow: [
    { label: "esc", w: 1.25, act: { key: "Escape" }, dark: true },
    { label: "tab", w: 1.25, act: { key: "Tab" }, dark: true },
    { label: "ctl", w: 1.25, act: { mod: "ctrl" }, dark: true },
    { label: "alt", w: 1.25, act: { mod: "alt" }, dark: true },
    { label: "pgu", w: 1.25, act: { key: "PageUp" }, dark: true },
    { label: "pgd", w: 1.25, act: { key: "PageDown" }, dark: true },
    { label: "settings", w: 2.5, act: { settings: true }, dark: true },
  ],
  layers: {
    lower: [
      [
        { label: "q", w: 1, act: { ch: "q" } },
        { label: "w", w: 1, act: { ch: "w" } },
        { label: "e", w: 1, act: { ch: "e" } },
        { label: "r", w: 1, act: { ch: "r" } },
        { label: "t", w: 1, act: { ch: "t" } },
        { label: "y", w: 1, act: { ch: "y" } },
        { label: "u", w: 1, act: { ch: "u" } },
        { label: "i", w: 1, act: { ch: "i" } },
        { label: "o", w: 1, act: { ch: "o" } },
        { label: "p", w: 1, act: { ch: "p" } },
      ],
      [
        { label: "a", w: 1, act: { ch: "a" } },
        { label: "s", w: 1, act: { ch: "s" } },
        { label: "d", w: 1, act: { ch: "d" } },
        { label: "f", w: 1, act: { ch: "f" } },
        { label: "g", w: 1, act: { ch: "g" } },
        { label: "h", w: 1, act: { ch: "h" } },
        { label: "j", w: 1, act: { ch: "j" } },
        { label: "k", w: 1, act: { ch: "k" } },
        { label: "l", w: 1, act: { ch: "l" } },
        { label: "'", w: 1, act: { ch: "'" } },
      ],
      [
        { label: "⇧", w: 1.5, act: { mod: "shift" }, dark: true },
        { label: "z", w: 1, act: { ch: "z" } },
        { label: "x", w: 1, act: { ch: "x" } },
        { label: "c", w: 1, act: { ch: "c" } },
        { label: "v", w: 1, act: { ch: "v" } },
        { label: "b", w: 1, act: { ch: "b" } },
        { label: "n", w: 1, act: { ch: "n" } },
        { label: "m", w: 1, act: { ch: "m" } },
        { label: "⌫", w: 1.5, act: { key: "Backspace" }, dark: true },
      ],
      [
        { label: "?123", w: 1.5, act: { layer: "sym" }, dark: true },
        { label: "-", w: 1, act: { ch: "-" } },
        { label: "space", w: 4, act: { ch: " " } },
        { label: "/", w: 1, act: { ch: "/" } },
        { label: ".", w: 1, act: { ch: "." } },
        { label: "⏎", w: 1.5, act: { key: "Enter" }, dark: true },
      ],
    ],
    upper: [
      [
        { label: "Q", w: 1, act: { ch: "Q" } },
        { label: "W", w: 1, act: { ch: "W" } },
        { label: "E", w: 1, act: { ch: "E" } },
        { label: "R", w: 1, act: { ch: "R" } },
        { label: "T", w: 1, act: { ch: "T" } },
        { label: "Y", w: 1, act: { ch: "Y" } },
        { label: "U", w: 1, act: { ch: "U" } },
        { label: "I", w: 1, act: { ch: "I" } },
        { label: "O", w: 1, act: { ch: "O" } },
        { label: "P", w: 1, act: { ch: "P" } },
      ],
      [
        { label: "A", w: 1, act: { ch: "A" } },
        { label: "S", w: 1, act: { ch: "S" } },
        { label: "D", w: 1, act: { ch: "D" } },
        { label: "F", w: 1, act: { ch: "F" } },
        { label: "G", w: 1, act: { ch: "G" } },
        { label: "H", w: 1, act: { ch: "H" } },
        { label: "J", w: 1, act: { ch: "J" } },
        { label: "K", w: 1, act: { ch: "K" } },
        { label: "L", w: 1, act: { ch: "L" } },
        { label: "\"", w: 1, act: { ch: "\"" } },
      ],
      [
        { label: "⬆", w: 1.5, act: { mod: "shift" }, dark: true },
        { label: "Z", w: 1, act: { ch: "Z" } },
        { label: "X", w: 1, act: { ch: "X" } },
        { label: "C", w: 1, act: { ch: "C" } },
        { label: "V", w: 1, act: { ch: "V" } },
        { label: "B", w: 1, act: { ch: "B" } },
        { label: "N", w: 1, act: { ch: "N" } },
        { label: "M", w: 1, act: { ch: "M" } },
        { label: "⌫", w: 1.5, act: { key: "Backspace" }, dark: true },
      ],
      [
        { label: "?123", w: 1.5, act: { layer: "sym" }, dark: true },
        { label: "_", w: 1, act: { ch: "_" } },
        { label: "space", w: 4, act: { ch: " " } },
        { label: "?", w: 1, act: { ch: "?" } },
        { label: "!", w: 1, act: { ch: "!" } },
        { label: "⏎", w: 1.5, act: { key: "Enter" }, dark: true },
      ],
    ],
    sym: [
      [
        { label: "1", w: 1, act: { ch: "1" } },
        { label: "2", w: 1, act: { ch: "2" } },
        { label: "3", w: 1, act: { ch: "3" } },
        { label: "4", w: 1, act: { ch: "4" } },
        { label: "5", w: 1, act: { ch: "5" } },
        { label: "6", w: 1, act: { ch: "6" } },
        { label: "7", w: 1, act: { ch: "7" } },
        { label: "8", w: 1, act: { ch: "8" } },
        { label: "9", w: 1, act: { ch: "9" } },
        { label: "0", w: 1, act: { ch: "0" } },
      ],
      [
        { label: "!", w: 1, act: { ch: "!" } },
        { label: "@", w: 1, act: { ch: "@" } },
        { label: "#", w: 1, act: { ch: "#" } },
        { label: "$", w: 1, act: { ch: "$" } },
        { label: "%", w: 1, act: { ch: "%" } },
        { label: "^", w: 1, act: { ch: "^" } },
        { label: "&", w: 1, act: { ch: "&" } },
        { label: "*", w: 1, act: { ch: "*" } },
        { label: "(", w: 1, act: { ch: "(" } },
        { label: ")", w: 1, act: { ch: ")" } },
      ],
      [
        { label: "#{~", w: 1.5, act: { layer: "sym2" }, dark: true },
        { label: "-", w: 1, act: { ch: "-" } },
        { label: "_", w: 1, act: { ch: "_" } },
        { label: "=", w: 1, act: { ch: "=" } },
        { label: "+", w: 1, act: { ch: "+" } },
        { label: "[", w: 1, act: { ch: "[" } },
        { label: "]", w: 1, act: { ch: "]" } },
        { label: ";", w: 1, act: { ch: ";" } },
        { label: "⌫", w: 1.5, act: { key: "Backspace" }, dark: true },
      ],
      [
        { label: "abc", w: 1.5, act: { layer: "lower" }, dark: true },
        { label: ":", w: 1, act: { ch: ":" } },
        { label: "space", w: 4, act: { ch: " " } },
        { label: ",", w: 1, act: { ch: "," } },
        { label: ".", w: 1, act: { ch: "." } },
        { label: "⏎", w: 1.5, act: { key: "Enter" }, dark: true },
      ],
    ],
    sym2: [
      [
        { label: "~", w: 1, act: { ch: "~" } },
        { label: "`", w: 1, act: { ch: "`" } },
        { label: "|", w: 1, act: { ch: "|" } },
        { label: "\\", w: 1, act: { ch: "\\" } },
        { label: "{", w: 1, act: { ch: "{" } },
        { label: "}", w: 1, act: { ch: "}" } },
        { label: "<", w: 1, act: { ch: "<" } },
        { label: ">", w: 1, act: { ch: ">" } },
        { label: "\"", w: 1, act: { ch: "\"" } },
        { label: "'", w: 1, act: { ch: "'" } },
      ],
      [
        { label: "F1+", w: 2, act: { layer: "fn" }, dark: true },
        { label: "*", w: 1, act: { ch: "*" } },
        { label: "+", w: 1, act: { ch: "+" } },
        { label: "-", w: 1, act: { ch: "-" } },
        { label: "=", w: 1, act: { ch: "=" } },
        { label: "%", w: 1, act: { ch: "%" } },
        { label: "$", w: 1, act: { ch: "$" } },
        { label: "#", w: 1, act: { ch: "#" } },
        { label: "@", w: 1, act: { ch: "@" } },
      ],
      [
        { label: "?123", w: 1.5, act: { layer: "sym" }, dark: true },
        { label: "&", w: 1, act: { ch: "&" } },
        { label: "^", w: 1, act: { ch: "^" } },
        { label: "!", w: 1, act: { ch: "!" } },
        { label: ".", w: 1, act: { ch: "." } },
        { label: ",", w: 1, act: { ch: "," } },
        { label: ";", w: 1, act: { ch: ";" } },
        { label: ":", w: 1, act: { ch: ":" } },
        { label: "⌫", w: 1.5, act: { key: "Backspace" }, dark: true },
      ],
      [
        { label: "abc", w: 1.5, act: { layer: "lower" }, dark: true },
        { label: "(", w: 1, act: { ch: "(" } },
        { label: "space", w: 4, act: { ch: " " } },
        { label: ")", w: 1, act: { ch: ")" } },
        { label: ".", w: 1, act: { ch: "." } },
        { label: "⏎", w: 1.5, act: { key: "Enter" }, dark: true },
      ],
    ],
    fn: [
      [
        { label: "F1", w: 2, act: { key: "F1" }, dark: true },
        { label: "F2", w: 2, act: { key: "F2" }, dark: true },
        { label: "F3", w: 2, act: { key: "F3" }, dark: true },
        { label: "F4", w: 2, act: { key: "F4" }, dark: true },
        { label: "F5", w: 2, act: { key: "F5" }, dark: true },
      ],
      [
        { label: "F6", w: 2, act: { key: "F6" }, dark: true },
        { label: "F7", w: 2, act: { key: "F7" }, dark: true },
        { label: "F8", w: 2, act: { key: "F8" }, dark: true },
        { label: "F9", w: 2, act: { key: "F9" }, dark: true },
        { label: "F10", w: 2, act: { key: "F10" }, dark: true },
      ],
      [
        { label: "F11", w: 2, act: { key: "F11" }, dark: true },
        { label: "F12", w: 2, act: { key: "F12" }, dark: true },
        { label: "ins", w: 2, act: { key: "Insert" }, dark: true },
        { label: "del", w: 2, act: { key: "Delete" }, dark: true },
        { label: "home", w: 2, act: { key: "Home" }, dark: true },
      ],
      [
        { label: "abc", w: 2, act: { layer: "lower" }, dark: true },
        { label: "?123", w: 2, act: { layer: "sym" }, dark: true },
        { label: "end", w: 2, act: { key: "End" }, dark: true },
        { label: "tab", w: 2, act: { key: "Tab" }, dark: true },
        { label: "enter", w: 2, act: { key: "Enter" }, dark: true },
      ],
    ],
  },
};
